CREATE TABLE clientes (
    id_cliente       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nome             VARCHAR2(150)      NOT NULL,
    email            VARCHAR2(150)      NOT NULL,
    cpf              VARCHAR2(11)       NOT NULL,
    telefone         VARCHAR2(20), --cadastro será feito com () e caracteres especiais para migração de whatsApp
    data_nascimento  DATE,
    
    -- Endereço
    cep              VARCHAR2(8),
    logradouro       VARCHAR2(200),
    numero           VARCHAR2(10),
    complemento      VARCHAR2(100),
    bairro           VARCHAR2(100),
    cidade           VARCHAR2(100),
    estado           VARCHAR2(2),

    -- Metadados
    data_cadastro    DATE DEFAULT SYSDATE,
    ativo            CHAR(1) DEFAULT 'S' CHECK (ativo IN ('S','N')),
    observacoes      CLOB,

    CONSTRAINT pk_clientes PRIMARY KEY (id_cliente),
    CONSTRAINT unq_clientes_email UNIQUE (email),
    CONSTRAINT unq_clientes_cpf UNIQUE (cpf)
);

-- para observações:

COMMENT ON TABLE clientes IS 'Tabela principal de clientes da loja';
COMMENT ON COLUMN clientes.id_cliente IS 'Chave primária do cliente';
COMMENT ON COLUMN clientes.ativo IS 'Indica se o cliente está ativo (S/N)';
COMMENT ON COLUMN clientes.observacoes IS 'Campo livre para observações gerais';

SELECT * FROM clientes;

    -- tabela de produtos:

CREATE TABLE produtos (
    id_produto        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nome              VARCHAR2(200)      NOT NULL,
    descricao         CLOB,
    categoria         VARCHAR2(100),
    marca             VARCHAR2(100),
    modelo            VARCHAR2(100),

    preco             NUMBER(10,2)       NOT NULL,
    quantidade_estoque NUMBER DEFAULT 0,
    unidade_medida    VARCHAR2(10) DEFAULT 'UN',

    -- Dados administrativos
    ativo             CHAR(1) DEFAULT 'S' CHECK (ativo IN ('S','N')),
    data_cadastro     DATE DEFAULT SYSDATE,
    data_atualizacao  DATE,

    -- Regras
    CONSTRAINT pk_produtos PRIMARY KEY (id_produto),
    CONSTRAINT chk_preco_positivo CHECK (preco >= 0),
    CONSTRAINT chk_estoque_positivo CHECK (quantidade_estoque >= 0)
);

    -- comentários para documentação: 

COMMENT ON TABLE produtos IS 'Tabela de produtos da loja';
COMMENT ON COLUMN produtos.preco IS 'Preço de venda do produto';
COMMENT ON COLUMN produtos.quantidade_estoque IS 'Quantidade disponível no estoque';
COMMENT ON COLUMN produtos.ativo IS 'Indica se o produto está ativo (S/N)';

    -- aumento de performance: 

CREATE INDEX idx_produtos_nome ON produtos (nome);
CREATE INDEX idx_produtos_categoria ON produtos (categoria);


-- vendas:

CREATE TABLE vendas (
    id_venda NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER NOT NULL,
    id_produto NUMBER NOT NULL,
    quantidade NUMBER NOT NULL,

    -- FK para o usuário/cliente
    CONSTRAINT fk_venda_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES clientes(id_cliente),

    -- FK para o produto
    CONSTRAINT fk_venda_produto
        FOREIGN KEY (id_produto)
        REFERENCES produtos(id_produto)
);

-- Insert na tabela clientes:

INSERT INTO clientes (nome, email, cpf, telefone, data_nascimento, cep, logradouro, numero, complemento, bairro, cidade, estado, observacoes)
VALUES (
    'Cliente 31',
    'cli031_2025@example.com',
    '90100000031',
    '(11)90001-0031',
    DATE '1990-07-01',
    '01431000',
    'Rua Nova Alpha',
    '131',
    NULL,
    'Centro',
    'Sao Paulo',
    'SP',
    NULL
);

INSERT INTO clientes (nome, email, cpf, telefone, data_nascimento, cep, logradouro, numero, complemento, bairro, cidade, estado, observacoes)
VALUES (
    'Mariana Silva',
    'mariana.silva@example.com',
    '90100000032',
    '(11)90001-0032',
    DATE '1992-03-15',
    '01431001',
    'Rua das Flores',
    '101',
    NULL,
    'Jardins',
    'Sao Paulo',
    'SP',
    NULL
);


INSERT INTO clientes (nome, email, cpf, telefone, data_nascimento, cep, logradouro, numero, complemento, bairro, cidade, estado, observacoes)
VALUES (
    'Lucas Pereira',
    'lucas.pereira@example.com',
    '90100000003',
    '(11)90001-0033',
    DATE '1988-07-22',
    '01432001',
    'Rua das Palmeiras',
    '102',
    NULL,
    'Moema',
    'Sao Paulo',
    'SP',
    NULL
);
INSERT INTO clientes (nome, email, cpf, telefone, data_nascimento, cep, logradouro, numero, complemento, bairro, cidade, estado, observacoes)
VALUES (
    'Camila Oliveira',
    'camila.oliveira@example.com',
    '90100000004',
    '(11)90001-0034',
    DATE '1990-11-05',
    '01432002',
    'Rua dos Jacarandás',
    '103',
    NULL,
    'Vila Mariana',
    'Sao Paulo',
    'SP',
    NULL
);

INSERT INTO clientes (nome, email, cpf, telefone, data_nascimento, cep, logradouro, numero, complemento, bairro, cidade, estado, observacoes)
VALUES (
    'Rafael Santos',
    'rafael.santos@example.com',
    '90100000005',
    '(11)90001-0035',
    DATE '1985-01-30',
    '01432003',
    'Rua do Sol',
    '104',
    NULL,
    'Pinheiros',
    'Sao Paulo',
    'SP',
    NULL
);

-- insert tabela produtos:

INSERT INTO produtos (nome, descricao, categoria, marca, modelo, preco, quantidade_estoque, unidade_medida)
VALUES (
    'Smartphone Galaxy S25',
    'Smartphone com 256GB, 12GB RAM, câmera tripla de 108MP',
    'Eletrônicos',
    'Samsung',
    'Galaxy S25',
    4999.90,
    50,
    'UN'
);

INSERT INTO produtos (nome, descricao, categoria, marca, modelo, preco, quantidade_estoque, unidade_medida)
VALUES (
    'Notebook ThinkPad X1',
    'Ultrabook com processador i7, 16GB RAM, SSD 512GB',
    'Informática',
    'Lenovo',
    'ThinkPad X1 Carbon',
    8499.00,
    30,
    'UN'
);

INSERT INTO produtos (nome, descricao, categoria, marca, modelo, preco, quantidade_estoque, unidade_medida)
VALUES (
    'Fone de Ouvido WH-1000XM5',
    'Fone Bluetooth com cancelamento de ruído, bateria 30h',
    'Eletrônicos',
    'Sony',
    'WH-1000XM5',
    1599.50,
    100,
    'UN'
);

INSERT INTO produtos (nome, descricao, categoria, marca, modelo, preco, quantidade_estoque, unidade_medida)
VALUES (
    'Cafeteira Expresso Barista',
    'Cafeteira automática com moedor integrado e vapor de leite',
    'Eletrodomésticos',
    'DeLonghi',
    'Barista EC685',
    1299.90,
    20,
    'UN'
);

INSERT INTO produtos (nome, descricao, categoria, marca, modelo, preco, quantidade_estoque, unidade_medida)
VALUES (
    'Bicicleta Mountain Bike XTR',
    'Bicicleta aro 29, 21 marchas, quadro de alumínio',
    'Esportes',
    'Caloi',
    'XTR 2025',
    2599.00,
    15,
    'UN'

);

-- insert para vendas

INSERT INTO vendas (id_usuario, id_produto, quantidade)
VALUES (
    31,  -- id do usuário Mariana Silva
    1,   -- id do produto Smartphone Galaxy S25
    2    -- quantidade comprada
);

INSERT INTO vendas (id_usuario, id_produto, quantidade)
VALUES (
    32,  -- id do usuário Lucas Pereira
    2,   -- id do produto Notebook ThinkPad X1
    1    -- quantidade comprada
);

INSERT INTO vendas (id_usuario, id_produto, quantidade)
VALUES (
    33,  -- id do usuário Camila Oliveira
    3,   -- id do produto Fone de Ouvido WH-1000XM5
    3    -- quantidade comprada
);

INSERT INTO vendas (id_usuario, id_produto, quantidade)
VALUES (
    34,  -- id do usuário Rafael Santos
    4,   -- id do produto Cafeteira Expresso Barista
    1    -- quantidade comprada
);
 
 INSERT INTO vendas (id_usuario, id_produto, quantidade)
VALUES (
    35,  -- id do usuário Beatriz Costa
    5,   -- id do produto Bicicleta Mountain Bike XTR
    2    -- quantidade comprada
);

-- Select para visualizar vendas:

SELECT 
    v.id_venda,
    c.nome AS clientes,
    p.nome AS produtos,
    v.id_venda AS vendas,
    p.categoria,
    p.marca,
    p.modelo,
    v.quantidade,
    p.preco,
    v.id_venda,
    (v.quantidade * p.preco) AS valor_total
FROM vendas v
LEFT JOIN clientes c ON v.id_usuario = c.id_cliente
LEFT JOIN produtos p ON v.id_produto = p.id_produto
ORDER BY v.id_venda;

SELECT * FROM vendas;

-- trigger para atualizar estoque após inserir uma venda na tabela vendas

CREATE OR REPLACE TRIGGER trg_atualiza_estoque
AFTER INSERT ON vendas
FOR EACH ROW
BEGIN
    -- Atualiza a quantidade em estoque do produto vendido
    UPDATE produtos
    SET quantidade_estoque = quantidade_estoque - :NEW.quantidade
    WHERE id_produto = :NEW.id_produto;
    
    -- Opcional: você pode adicionar verificação de estoque negativo
    -- IF (quantidade_estoque - :NEW.quantidade < 0) THEN
    --    RAISE_APPLICATION_ERROR(-20001, 'Estoque insuficiente!');
    -- END IF;
END;
/

-- Procedure para registrar uma venda:

CREATE OR REPLACE PROCEDURE registrar_venda (
    p_id_cliente IN NUMBER,
    p_id_produto IN NUMBER,
    p_quantidade IN NUMBER,
    p_msg OUT VARCHAR2
)
AS
    v_estoque_atual NUMBER;
BEGIN
    -- Verifica se o cliente existe e está ativo
    DECLARE
        v_cliente_ativo CHAR(1);
    BEGIN
        SELECT ativo
        INTO v_cliente_ativo
        FROM clientes
        WHERE id_cliente = p_id_cliente;

        IF v_cliente_ativo = 'N' THEN
            p_msg := 'Cliente inativo. Venda não realizada.';
            RETURN;
        END IF;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            p_msg := 'Cliente não encontrado. Venda não realizada.';
            RETURN;
    END;

    -- Verifica se o produto existe e está ativo
    DECLARE
        v_produto_ativo CHAR(1);
    BEGIN
        SELECT ativo
        INTO v_produto_ativo
        FROM produtos
        WHERE id_produto = p_id_produto;

        IF v_produto_ativo = 'N' THEN
            p_msg := 'Produto inativo. Venda não realizada.';
            RETURN;
        END IF;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            p_msg := 'Produto não encontrado. Venda não realizada.';
            RETURN;
    END;

    -- Verifica estoque disponível
    SELECT quantidade_estoque
    INTO v_estoque_atual
    FROM produtos
    WHERE id_produto = p_id_produto;

    IF v_estoque_atual < p_quantidade THEN
        p_msg := 'Estoque insuficiente. Venda não realizada.';
        RETURN;
    END IF;

    -- Insere a venda
    INSERT INTO vendas (id_usuario, id_produto, quantidade)
    VALUES (p_id_cliente, p_id_produto, p_quantidade);

    -- Atualiza o estoque do produto
    UPDATE produtos
    SET quantidade_estoque = quantidade_estoque - p_quantidade
    WHERE id_produto = p_id_produto;

    p_msg := 'Venda realizada com sucesso!';
EXCEPTION
    WHEN OTHERS THEN
        p_msg := 'Erro inesperado: ' || SQLERRM;
END;
/
-- usar a procedure: 

DECLARE
    v_mensagem VARCHAR2(200);
BEGIN
    registrar_venda(1, 1, 2, v_mensagem); -- Cliente 1 compra 2 unidades do produto 1
    DBMS_OUTPUT.PUT_LINE(v_mensagem);
END;
/

SELECT * FROM VENDAS;

-- procedure para cancelar uma venda:

CREATE OR REPLACE PROCEDURE cancelar_venda (
    p_id_venda IN NUMBER,
    p_msg OUT VARCHAR2
)
AS
    v_id_produto NUMBER;
    v_quantidade NUMBER;
BEGIN
    -- Verifica se a venda existe e captura produto e quantidade
    BEGIN
        SELECT id_produto, quantidade
        INTO v_id_produto, v_quantidade
        FROM vendas
        WHERE id_venda = p_id_venda;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            p_msg := 'Venda não encontrada.';
            RETURN;
    END;

    -- Remove a venda
    DELETE FROM vendas
    WHERE id_venda = p_id_venda;

    -- Devolve o estoque do produto
    UPDATE produtos
    SET quantidade_estoque = quantidade_estoque + v_quantidade
    WHERE id_produto = v_id_produto;

    p_msg := 'Venda cancelada com sucesso e estoque atualizado.';
EXCEPTION
    WHEN OTHERS THEN
        p_msg := 'Erro inesperado: ' || SQLERRM;
END;
/

-- usar:

DECLARE
    v_mensagem VARCHAR2(200);
BEGIN
    cancelar_venda(1, v_mensagem); -- Cancela a venda com id_venda = 1
    DBMS_OUTPUT.PUT_LINE(v_mensagem);
END;
/


