-querys TABELAS:

CREATE TABLE clientes (
    id_cliente       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nome             VARCHAR2(150)      NOT NULL,
    email            VARCHAR2(150)      NOT NULL,
    cpf              VARCHAR2(11)       NOT NULL,
    telefone         VARCHAR2(20), --cadastro será feito com () e caracteres especiais para migração de whatsApp
    data_nascimento  DATE,
    
    -- Endereço
    cep              VARCHAR2(8),
    logradouro       VARCHAR2(200),
    numero           VARCHAR2(10),
    complemento      VARCHAR2(100),
    bairro           VARCHAR2(100),
    cidade           VARCHAR2(100),
    estado           VARCHAR2(2),

    -- Metadados
    data_cadastro    DATE DEFAULT SYSDATE,
    ativo            CHAR(1) DEFAULT 'S' CHECK (ativo IN ('S','N')),
    observacoes      CLOB,

    CONSTRAINT pk_clientes PRIMARY KEY (id_cliente),
    CONSTRAINT unq_clientes_email UNIQUE (email),
    CONSTRAINT unq_clientes_cpf UNIQUE (cpf)
);

-- para observações:

COMMENT ON TABLE clientes IS 'Tabela principal de clientes da loja';
COMMENT ON COLUMN clientes.id_cliente IS 'Chave primária do cliente';
COMMENT ON COLUMN clientes.ativo IS 'Indica se o cliente está ativo (S/N)';
COMMENT ON COLUMN clientes.observacoes IS 'Campo livre para observações gerais';

SELECT * FROM clientes;

    -- tabela de produtos:

CREATE TABLE produtos (
    id_produto        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nome              VARCHAR2(200)      NOT NULL,
    descricao         CLOB,
    categoria         VARCHAR2(100),
    marca             VARCHAR2(100),
    modelo            VARCHAR2(100),

    preco             NUMBER(10,2)       NOT NULL,
    quantidade_estoque NUMBER DEFAULT 0,
    unidade_medida    VARCHAR2(10) DEFAULT 'UN',

    -- Dados administrativos
    ativo             CHAR(1) DEFAULT 'S' CHECK (ativo IN ('S','N')),
    data_cadastro     DATE DEFAULT SYSDATE,
    data_atualizacao  DATE,

    -- Regras
    CONSTRAINT pk_produtos PRIMARY KEY (id_produto),
    CONSTRAINT chk_preco_positivo CHECK (preco >= 0),
    CONSTRAINT chk_estoque_positivo CHECK (quantidade_estoque >= 0)
);

    -- comentários para documentação: 

COMMENT ON TABLE produtos IS 'Tabela de produtos da loja';
COMMENT ON COLUMN produtos.preco IS 'Preço de venda do produto';
COMMENT ON COLUMN produtos.quantidade_estoque IS 'Quantidade disponível no estoque';
COMMENT ON COLUMN produtos.ativo IS 'Indica se o produto está ativo (S/N)';

    -- aumento de performance: 

CREATE INDEX idx_produtos_nome ON produtos (nome);
CREATE INDEX idx_produtos_categoria ON produtos (categoria);


-- vendas:

CREATE TABLE vendas (
    id_venda NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER NOT NULL,
    id_produto NUMBER NOT NULL,
    quantidade NUMBER NOT NULL,

    -- FK para o usuário/cliente
    CONSTRAINT fk_venda_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES clientes(id_cliente),

    -- FK para o produto
    CONSTRAINT fk_venda_produto
        FOREIGN KEY (id_produto)
        REFERENCES produtos(id_produto)
);
